<a href="https://colab.research.google.com/github/Sinrez/PythonProjects/blob/main/hw_pandas_in_act_6_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Наш набор данных покупателей включает столбец Address Адреса состоят из улицы, города, штата и почтового индекса Ваша задача: разбить эти четыре значения по четырем новым столбцам Street, City, State и Zip, после чего уда- лить исходный столбец Address Попробуйте решить эту задачу самостоятельно, а затем можете заглянуть в решение

In [3]:
import pandas as pd
customers = pd.read_csv("customers.csv")
customers.head()

                  Name                                            Address
0        Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1    Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2      Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3  Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4       Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...

In [7]:
# expand - возвращаем DataFrame
addr = customers['Address'].str.split(',', expand = True)
addr.head()

                            0              1               2       3
0           6461 Quinn Groves   East Matthew   New Hampshire   16656
1  1360 Tracey Ports Apt. 419       Kyleport         Vermont   31924
2        19120 Fleming Manors    Prestonstad         Montana   23495
3            441 Olivia Creek     Jimmymouth         Georgia   82991
4  4246 Chelsey Ford Apt. 310      Karamouth            Utah   76252

In [9]:
customers[['Street', 'City', 'State', 'Zip']] = addr
customers.head()

,Name,Address,Street,City,State,Zip
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252

In [10]:
customers = customers.drop('Address', axis=1)
customers.head()

,Name,Street,City,State,Zip
0,Frank Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252

In [11]:
customers[['First Name', 'Last Name']] = customers['Name'].str.split(pat = " ", expand = True, n =1)
customers.head()

,Name,Street,City,State,Zip,First Name,Last Name
0,Frank Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656,Frank,Manning
1,Elizabeth Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924,Elizabeth,Johnson
2,Donald Stephens,19120 Fleming Manors,Prestonstad,Montana,23495,Donald,Stephens
3,Michael Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991,Michael,Vincent III
4,Jasmine Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252,Jasmine,Zamora

In [12]:
customers = customers.drop('Name', axis=1)
customers.head()

,Street,City,State,Zip,First Name,Last Name
0,6461 Quinn Groves,East Matthew,New Hampshire,16656,Frank,Manning
1,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924,Elizabeth,Johnson
2,19120 Fleming Manors,Prestonstad,Montana,23495,Donald,Stephens
3,441 Olivia Creek,Jimmymouth,Georgia,82991,Michael,Vincent III
4,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252,Jasmine,Zamora